fix: `utils` replace map (#1632)
Methods must be wrapped by a `lambda`, othwerwise they get called on
symbol access.

```py
/.../viur/core/module.py:245 [WARNING] Use of `utils.generateRandomString` is deprecated; Use `utils.string.random` instead!
/.../viur/core/request.py:400 [ERROR] ViUR has caught an unhandled exception!
/.../viur/core/request.py:401 [ERROR] 'str' object is not callable
Traceback (most recent call last):
    log.debug(f"{utils.getCurrentUser()=}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not callable
```

```py
/.../viur/core/module.py:245 [WARNING] Use of `utils.escapeString` is deprecated; Use `utils.string.escape` instead!
/.../viur/core/request.py:400 [ERROR] ViUR has caught an unhandled exception!
/.../viur/core/request.py:401 [ERROR] escape() missing 1 required positional argument: 'val'
Traceback (most recent call last):
    log.debug(f"{utils.escapeString("hello world #ä+-#d")=}")
                 ^^^^^^^^^^^^^^^^^^
  File "/viur-core/src/viur/core/utils/__init__.py", line 212, in __getattr__
    res = res()
TypeError: escape() missing 1 required positional argument: 'val'
```

---------

Co-authored-by: agudermann <47318461+ArneGudermann@users.noreply.github.com>